/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttendanceError = { 'subjectNotFound' : SubjectId } |
  { 'notAuthorized' : null } |
  { 'notFound' : AttendanceId } |
  { 'invalidDate' : null };
export type AttendanceId = bigint;
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null } |
  { 'classCancelled' : null };
export interface AttendanceView {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'date' : DateKey,
  'updatedAt' : bigint,
  'subjectId' : SubjectId,
}
export interface Cell { 'value' : Value, 'name' : string }
export type ColourHex = string;
export type DateKey = string;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type Result = { 'ok' : AttendanceView } |
  { 'err' : AttendanceError };
export type Result_1 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type SubjectError = { 'notAuthorized' : null } |
  { 'notFound' : SubjectId } |
  { 'invalidName' : null } |
  { 'invalidColour' : null };
export type SubjectId = bigint;
export interface SubjectView {
  'id' : SubjectId,
  'name' : string,
  'createdAt' : bigint,
  'colour' : ColourHex,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a subject owned by the signed-in caller.
   */
  'createSubject' : ActorMethod<[string, ColourHex], SubjectView>,
  /**
   * / Delete one of the signed-in caller's attendance records.
   */
  'deleteAttendance' : ActorMethod<[AttendanceId], [] | [AttendanceError]>,
  /**
   * / Delete one of the signed-in caller's subjects.
   */
  'deleteSubject' : ActorMethod<[SubjectId], [] | [SubjectError]>,
  /**
   * / Delete a subject and every attendance record that belongs to it.
   */
  'deleteSubjectWithAttendance' : ActorMethod<[SubjectId], [] | [SubjectError]>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Static Markdown description of this canister's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the signed-in caller's attendance records for a subject.
   */
  'listAttendance' : ActorMethod<[SubjectId], Array<AttendanceView>>,
  /**
   * / List the signed-in caller's subjects.
   */
  'listSubjects' : ActorMethod<[], Array<SubjectView>>,
  /**
   * / Record or update attendance for one of the signed-in caller's subjects.
   */
  'recordAttendance' : ActorMethod<
    [SubjectId, DateKey, AttendanceStatus],
    Result
  >,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];