/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ColourHex = IDL.Text;
export const SubjectId = IDL.Nat;
export const SubjectView = IDL.Record({
  'id' : SubjectId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'colour' : ColourHex,
});
export const AttendanceId = IDL.Nat;
export const AttendanceError = IDL.Variant({
  'subjectNotFound' : SubjectId,
  'notAuthorized' : IDL.Null,
  'notFound' : AttendanceId,
  'invalidDate' : IDL.Null,
});
export const SubjectError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : SubjectId,
  'invalidName' : IDL.Null,
  'invalidColour' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
  'classCancelled' : IDL.Null,
});
export const DateKey = IDL.Text;
export const AttendanceView = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'date' : DateKey,
  'updatedAt' : IDL.Int,
  'subjectId' : SubjectId,
});
export const Result = IDL.Variant({
  'ok' : AttendanceView,
  'err' : AttendanceError,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSubject' : IDL.Func([IDL.Text, ColourHex], [SubjectView], []),
  'deleteAttendance' : IDL.Func([AttendanceId], [IDL.Opt(AttendanceError)], []),
  'deleteSubject' : IDL.Func([SubjectId], [IDL.Opt(SubjectError)], []),
  'deleteSubjectWithAttendance' : IDL.Func(
      [SubjectId],
      [IDL.Opt(SubjectError)],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAttendance' : IDL.Func(
      [SubjectId],
      [IDL.Vec(AttendanceView)],
      ['query'],
    ),
  'listSubjects' : IDL.Func([], [IDL.Vec(SubjectView)], ['query']),
  'recordAttendance' : IDL.Func(
      [SubjectId, DateKey, AttendanceStatus],
      [Result],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ColourHex = IDL.Text;
  const SubjectId = IDL.Nat;
  const SubjectView = IDL.Record({
    'id' : SubjectId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'colour' : ColourHex,
  });
  const AttendanceId = IDL.Nat;
  const AttendanceError = IDL.Variant({
    'subjectNotFound' : SubjectId,
    'notAuthorized' : IDL.Null,
    'notFound' : AttendanceId,
    'invalidDate' : IDL.Null,
  });
  const SubjectError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : SubjectId,
    'invalidName' : IDL.Null,
    'invalidColour' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
    'classCancelled' : IDL.Null,
  });
  const DateKey = IDL.Text;
  const AttendanceView = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'date' : DateKey,
    'updatedAt' : IDL.Int,
    'subjectId' : SubjectId,
  });
  const Result = IDL.Variant({
    'ok' : AttendanceView,
    'err' : AttendanceError,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSubject' : IDL.Func([IDL.Text, ColourHex], [SubjectView], []),
    'deleteAttendance' : IDL.Func(
        [AttendanceId],
        [IDL.Opt(AttendanceError)],
        [],
      ),
    'deleteSubject' : IDL.Func([SubjectId], [IDL.Opt(SubjectError)], []),
    'deleteSubjectWithAttendance' : IDL.Func(
        [SubjectId],
        [IDL.Opt(SubjectError)],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAttendance' : IDL.Func(
        [SubjectId],
        [IDL.Vec(AttendanceView)],
        ['query'],
      ),
    'listSubjects' : IDL.Func([], [IDL.Vec(SubjectView)], ['query']),
    'recordAttendance' : IDL.Func(
        [SubjectId, DateKey, AttendanceStatus],
        [Result],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };